model: informer
data: stock
root_path: E:\workspace\datasets\stock_market_data\forbes2000\csv
learning_rate: 0.0001
batch_size: 32
features: MS
seq_len: 64
label_len: 64
pred_len: 1
e_layers: 2
d_layers: 1
attn: prob
target: Close
data_path: 'GOOG.csv'
enc_in: 5
dec_in: 5
c_out: 1
des: Exp
itr: 1
factor: 3
freq: d
train_epochs: 200
mode: test
ckpt_file: E:\workspace\stock_prediction\informer\checkpoints\informer_stock_ftMS_sl64_ll64_pl1_dm512_nh8_el2_dl1_df2048_atprob_fc3_ebtimeF_dtTrue_mxTrue_Exp_0\checkpoint.pth
inverse: False
inverse_result: True